### ISSUE TITLE
Network error on 4.1.3

### ISSUE THREAD

**Issue by ednolan** [inderdhir/DatWeatherDoe#137]
I updated to 4.1.3 and now I only ever see "Network Error," it shows up immediately on startup and does not go away after a refresh. Is there any way to debug this?

**Comment by inderdhir** [comment]
I just did a fresh install and it seems to be working on my end. 

Can you try using Proxyman/Charles and check if the `appId` query parameter is present when the app makes a call to the API? You can try clicking "Refresh" or changing the app configuration to trigger a refresh so that it shows up.

<img width="343" alt="Screenshot 2024-03-27 at 4 06 48 PM" src="https://github.com/inderdhir/DatWeatherDoe/assets/2235307/d92bab38-fa19-44a0-a59f-5d0d4f9dc9ce">

**Comment by ednolan** [comment]
I installed Proxyman and DatWeatherDoe doesn't show up as making requests at all. I tried clicking refresh and changing the app configuration, neither of those had any effect.

**Comment by ednolan** [comment]
Same thing after updating to 4.2.0.

**Comment by miss4chewN8** [comment]
@ednolan I was facing the same issue when I updated to this app via an Ethernet connection. I tried everything and the "Network Error" message just didn't stop persisting. I gave up on the app and installed "Sparrow Weather" from the App Store and noticed that it wasn't refreshing as well. In the FAQ of that app, it was mentioned that the app uses WiFi to analyse the location and hence it won't work on wired internet connections. 

Then I tried connecting to WiFi and DatWeatherDoe 4.2.0 worked! Please give it a try again in case you were connected via Ethernet earlier.

**Comment by ednolan** [comment]
Yes, I also was using Ethernet and I had WiFi turned off.

**Comment by inderdhir** [comment]
I added a change in 4.2.1 that should better surface errors on the UI. Thanks for the help @miss4chewN8
