### ISSUE TITLE
"The data couldn't be read because it is missing" error

### ISSUE THREAD

**Issue by miss4chewN8** [inderdhir/DatWeatherDoe#155]
The menubar app displays the above message and doesn't work with Lat/Long either. Upon clicking the "See Full Weather" button, I am led to the right location on the weather.api website. 

Location services are working with other apps.

**Comment by luckman212** [comment]
Same for me...

![screenshot_AV8XG7M9](https://github.com/user-attachments/assets/0dcda37d-2a73-4d18-b9b1-42aea5134b40)

**Comment by sluan-design** [comment]
Me too. The location function doesn't work.  Even to reinstall App or del the old version and install a new app. There is only one way to collect the data by Lat/Lone. But when the mac restarted, all the Lat/Long invalid. and I have to reconfigure the location data.

**Comment by miss4chewN8** [comment]
It seems to be working again. Maybe it was a WeatherAPI issue.

**Comment by miss4chewN8** [comment]
It works but the weather reading has been stuck at a particular value for me.

**Comment by luckman212** [comment]
May I suggest:

Instead of the very long **_The data couldn't be read because it is missing_** message when the API is down or returning garbage (which forces all other menubar items to the left, and thus out of reach or hidden most of the time) maybe just add a ⚠️ emoji symbol to the last valid temp to indicate there was a problem fetching data. Or if symbol is not preferred, then just a simple **??°F** would be fine by me.

**Comment by inderdhir** [comment]
This was fixed in one place but I believe there's another codepath where this can be fixed.

**Comment by inderdhir** [comment]
Fixed in 5.2.1!
